server:
  port: 8886
spring:
  main:
    web-application-type: reactive
  data:
    mongodb:
      port: 27017
      database: vilya_be
      host: localhost
  liquibase:
    change-log: classpath:/mongo/changelog-master.xml

app:
  jwt:
    signing-key: MUFEQUI2NTcxPDUyRUNBNkA2QzI4QkFFNTk4XUQxNkQ=
    access-token-expiration: 7d
    issuer: https://vilya.com

springdoc:
  api-docs:
    path: /v3/swagger-ui.html
  swagger-ui:
    path: /v3/api-docs

